= TSC Meeting - September 23rd, 2021

:sectnums:
:nofooter:
:icons: font

****
Proposed Agenda
****

== Status of actions from previous TSC meeting

* Cancelling recurring TSC invitations from Hanae: Not doable, please delete them from your calendars (they're only for 2021)
* Can anyone write back to the TSC mailing list to propose topics? Checked on the admin interface -> OK
* Investigate moving from Jira to GitHub issues (script it?) -> we actually even went ahead with it! OK
* Create and start using Slack channel on the LFEnergy Slack instead of project Slack -> OK

== 20/07/2021 TAC meeting

* LFE has established its own DockerHub account
* Calls to share any planned project or community meetings that could be interesting for other projects
* LFE wants to have TFiR do video interviews of all projects, preferably before the end of the year
** 7/10 minutes long
** Good opportunity to have promotion material for the project
** TODO: Prepare possible questions/discussion topics then send an email to marketing@lfenergy.org to get on the schedule
* Security Working Group

* OperatorFabric Annual Review
** Share slide deck? Where?
** Committers file: initialized, future changes will need to be approved by TSC
** Growth Plan
** Questions about the geographical visualization of data and PowSyBl/GridSuite
** MMI mentioned that project SOGNO was presented this year (March) to the conference
https://www.smartgrid-forums.com/past-presentations[NextGen SCADA Europe 2021], and that it could be a good place to
present OperatorFabric next year.

== Status of current DockerHub use vs limitations (in relation with LFE DockerHub account topic)

=== Image retention
From https://www.docker.com/blog/docker-hub-image-retention-policy-delayed-and-subscription-updates/[this blog]
it looks like limitations on image retention as initially announced by DockerHub in late October 2020 are no longer in
order. All the OperatorFabric versions ever published are still available on DockerHub.

=== Pull rate limit
200 pulls / 6h for authenticated users (see https://www.docker.com/pricing), 100 for anonymous users.
Unlikely to be an issue for developers locally.
Our Travis CI pipeline uses an authenticated users (service account), and has to pull 3 images/build (RabbitMQ, MongoDB
and Keycloak) so that's over 265 builds / 24h. The number of pulls/build might increase if we parallelize some stages
of the build but even 9/builds would let us do around 90 builds / 24h.

=== Support for open source projects
It's possible to
https://www.docker.com/blog/expanded-support-for-open-source-software-projects/[apply for open source project qualification]
to raise the pull limit.

== Other possible topics

=> Ask on Slack or mailing list

* Internationalization is curtailing text search possibilities
* Setting up two-factor auth
* Minimal testing setup for the Kafka connection (ideally automated)
* NRI mentioned in closing that he saw parallels with other projects, maybe that's something that we can discuss further
in our next meeting?
* Experience with Cypress tests





