= TSC Meeting - April 21th, 2022 , 09:30 am  

:sectnums:
:nofooter:
:icons: font

Participants:: Gerben Danen (Alliander), Frédéric Didier (RTE), Boris Dolley (RTE), Jeroen Gommans (Alliander), Jelte Leijenaar (Alliander), Floris van der Meulen (Alliander), Olivier Pigeon (RTE).

== Presentation of main features introduce by release 3.6.0 

- **Show card acknowledgment in realtime** for card emitter.
- **Pinned cards**  :  Discussion in the meeting regarding the design, Alliander proposed to have the pinned cards on top of the feed. The subject will be discuss on next TSC meeting. In between, one can open a discussion on github.
- **View child cards in archive detail cards**
- **Do not allow the same user to be connected twice at the same time** : we do not permit to have the same user connected twice at the same time as for the time being the tool is not supported this use case (it has not be design for it). The option can be activated/deactivated at the instance level. 
We shared the fact that we may have use cases that need to have the same user connected two times
(for example mobile + laptop), if it is the case  the solution will have to evolve to permit it (there's no known technical limitation).
 
== Main future evolutions 

- Grouping cards in feed: demonstration form Alliander during the meeting 
- New multi-select component: https://github.com/opfab/operatorfabric-core/issues/2868

== Dev tools

- New cypress test possibilities implemented on CI github action :  
  * Option to launch only a subset af test 
  * Store the screenshots as github artifacts in case of test failing
- Proposal to use prettier as tool to lint the code

== Github discussions  

We now use labels "Discussion closed" and "Open discussion" to distinguish closed and open discussions.

== Misc 

For Next TSC, we shall have a look to the roadmap and fix priorities.

== Next TSC meeting

Next TSC meeting is schedule on May 26th, 2022 , 09:30 am 

