= TSC Meeting - April 3th, 2024 , 10:00 am  

:sectnums:
:nofooter:
:icons: font

Participants::

- Gerben Danen (Alliander)
- Frédéric Didier (RTE)
- Giovanni Ferrari (SoftLab)
- Valérie Longa (RTE)
- Olivier Voron (RTE-i)


== MongoDB Support 

Following last TSC, we now support MongoDB starting from version 4.4.0. 

== Last release


Version 4.2.1 is now the latest release of the software. Details can be found here: https://github.com/opfab/operatorfabric-core/releases/tag/4.2.0.RELEASE



== Next release

The next release is planned for the end of April, with a release candidate. 

The existing features are described in the draft release notes: https://github.com/opfab/release-notes/blob/master/release_notes.4.3.0.md

The main features planned for development include:

   - https://github.com/opfab/operatorfabric-core/issues/6181
   - https://github.com/opfab/operatorfabric-core/issues/6183
   - Features to enhance the monitoring process screen 
   - Add Kafka support for card action field (https://github.com/opfab/operatorfabric-core/issues/6008)

== 3.15.5 Release support

There is currently no immediate need for a 3.15.6 release as there are no dependencies requiring security patches.


== OperatorFabric interface 

A end user ask for either a Python client library or a RabbitMQ connector to exchange card.

Python could be an opportunity to develop a client library for the OperatorFabric API.

RabbitMQ does not seems to be interesting for the moment as we have a Kafka connector.

== Security documentation 

Security documentation is now available at https://opfab.github.io/documentation/current/security/. 


== Security Improvements

To enhance security, we should focus on the following areas:

- Docker signing: Implement a process to sign Docker images to ensure their authenticity and integrity.
- Enforcement commit signing: Enforce commit signing to verify the authenticity of code changes.
- Automated security checks for handlebars templates: Utilize tools like SonarQube to automatically scan handlebars templates for security vulnerabilities.

== Next TSC meeting

Next TSC meeting is schedule on 15th of May, 2024 at 10:00 am.